import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/navbar/Header";
import Footer from "@/components/shared/footer/Footer";
import PageTransition from "@/components/shared/component/PageTransition";
import StairTransition from "@/components/shared/component/StairTransition";
import { ScrollToTop } from "@/components/shared/component/ScrollTooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-darkBlack min-h-screen text-white">
          <Header />
          <StairTransition />
          <main className="px-4 sm:px-8 md:px-16 lg:px-32 xl:px-64 2xl:px-84">
            <PageTransition>
              {children}
              <ScrollToTop />
            </PageTransition>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
